### ISSUE TITLE
error creating npm install of your code

### ISSUE THREAD

**Issue by logix5** [fontainejp/blocklino#14]
I have this error when execute as administrator this command:

**$ npm install**
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> @serialport/bindings@2.0.8 install C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=win32)

C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
c:\users\usuario\documents\version1.4\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(329): error C2661: 'v8::Object::Set': ninguna función sobrecargada acepta 2 argumentos [C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\usuario\documents\version1.4\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(330): error C2661: 'v8::Object::Set': ninguna función sobrecargada acepta 2 argumentos [C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\usuario\documents\version1.4\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(331): error C2661: 'v8::Object::Set': ninguna función sobrecargada acepta 2 argumentos [C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
c:\users\usuario\documents\version1.4\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(378): error C2661: 'v8::Object::Set': ninguna función sobrecargada acepta 2 argumentos [C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Usuario\Documents\Version1.4\blocklino\node_modules\@serialport\bindings
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2021-01-06T19_59_45_028Z-debug.log

¿can you help me?

**Comment by fontainejp** [comment]
Hi,
it's probably due to the serialport module npm and i probably update it this summer.
Try to execute as administrator this command : 
`npm install serialport@7.1.4`
Bye
