### ISSUE TITLE
Install failed after downloading 

### ISSUE THREAD

**Issue by keyestudio2019** [fontainejp/blocklino#19]
hello， thanks for your open source code,
But I got an installation error after downloading them.
$ npm install

> @serialport/bindings@2.0.8 install E:\blocklino\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install connect ETIMEDOUT 20.205.243.166:443

E:\blocklino\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
e:\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(329): error C2661: “v8::Object::Set”: 没有重载函数接受 2 个参数 [E:\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
e:\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(330): error C2661: “v8::Object::Set”: 没有重载函数接受 2 个参数 [E:\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
e:\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(331): error C2661: “v8::Object::Set”: 没有重载函数接受 2 个参数 [E:\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
e:\blocklino\node_modules\@serialport\bindings\src\serialport.cpp(378): error C2661: “v8::Object::Set”: 没有重载函数接受 2 个参数 [E:\blocklino\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\blocklino\node_modules\@serialport\bindings
gyp ERR! node -v v14.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zuoke\AppData\Roaming\npm-cache\_logs\2023-06-28T06_35_22_473Z-debug.log

**Comment by keyestudio2019** [comment]
My environment configuration is  python 2.7    node  v14.21.0       Visual Studio 2017
